In [6]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier

In [7]:
import numpy as np 
import matplotlib.pyplot as plt

In [8]:
from sklearn.datasets import load_digits
digit = load_digits()

In [9]:
from sklearn.model_selection import train_test_split

In [31]:
xtrain  , xtest , ytrain , ytest = train_test_split(digit.data , digit.target , test_size=0.2)

In [32]:
lr = LogisticRegression()
lr.fit(xtrain,ytrain)
lr.score(xtest,ytest)

c:\Users\pc\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9472222222222222

In [33]:
sm = SVC()
sm.fit(xtrain,ytrain)
sm.score(xtest,ytest)

0.9833333333333333

In [34]:
rf = RandomForestClassifier()
rf.fit(xtrain,ytrain)
rf.score(xtest,ytest)

0.9583333333333334

In [36]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [38]:
for train_iundex , test_index in  kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_iundex , test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [39]:
def get_score(model , xtrain , xtest , ytrain , ytest ):
    model.fit(xtrain,ytrain)
    return model.score(xtest , ytest)

In [40]:
get_score(SVC() ,  xtrain , xtest , ytrain , ytest)

0.9833333333333333

In [42]:
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits=3)

In [55]:
score_logistic = [] 
score_svm = [] 
score_rf = []
for train_index , test_index in folds.split(digit.data , digit.target):
     x_train , x_test , y_train , y_test = digit.data[train_index] , digit.data[test_index] , digit.target[train_index] , digit.target[test_index]
     score_logistic.append(get_score(LogisticRegression() , x_train , x_test , y_train , y_test))
     score_svm.append(get_score(SVC() , x_train , x_test , y_train , y_test))
     score_rf.append(get_score(RandomForestClassifier(), x_train , x_test , y_train , y_test))

c:\Users\pc\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
c:\Users\pc\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/m

In [56]:
score_logistic

[0.9215358931552587, 0.9415692821368948, 0.9165275459098498]

In [57]:
score_svm

[0.9649415692821369, 0.9799666110183639, 0.9649415692821369]

In [58]:
score_rf

[0.9382303839732888, 0.9599332220367279, 0.9165275459098498]

In [59]:
from sklearn.model_selection import  cross_val_score

In [61]:
cross_val_score(LogisticRegression() , digit.data , digit.target)

c:\Users\pc\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
c:\Users\pc\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/m

array([0.92222222, 0.86944444, 0.94150418, 0.93871866, 0.89693593])

In [62]:
cross_val_score(SVC() , digit.data , digit.target)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [63]:
cross_val_score(RandomForestClassifier() , digit.data , digit.target)

array([0.93611111, 0.91666667, 0.96657382, 0.97214485, 0.92200557])