In [14]:
import pandas as pd
import numpy as np 
from sklearn import  linear_model

In [15]:
df = pd.read_csv("homeprices.csv")
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [16]:
import math
df.bedrooms.median()

4.0

In [18]:
df.bedrooms = df.bedrooms.fillna(df.bedrooms.median())
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [20]:
model = linear_model.LinearRegression()

In [22]:
model.fit(df.drop('price' , axis='columns'),df.price)

LinearRegression()

In [23]:
model.predict([[3000,3,40]])

/Users/akash/Library/Python/3.8/lib/python/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([498408.25158031])

In [28]:
model.predict([[2500,4,5]])

/Users/akash/Library/Python/3.8/lib/python/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([578876.03748933])

In [25]:
model.coef_

array([  112.06244194, 23388.88007794, -3231.71790863])

In [26]:
model.intercept_

221323.00186540408

In [27]:
vars(model)


{'fit_intercept': True,
 'normalize': 'deprecated',
 'copy_X': True,
 'n_jobs': None,
 'positive': False,
 'feature_names_in_': array(['area', 'bedrooms', 'age'], dtype=object),
 'n_features_in_': 3,
 'coef_': array([  112.06244194, 23388.88007794, -3231.71790863]),
 '_residues': 2677830769.346958,
 'rank_': 3,
 'singular_': array([1.31468830e+03, 1.66699701e+01, 6.77842492e-01]),
 'intercept_': 221323.00186540408}